/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:e2359fa7-7ca4-48f7-b309-3e1a461a3043",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_CZWdw0Zdb",
    "aws_user_pools_web_client_id": "5gf1e0ipt6jh68ofinvimk58dh",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "bookstore01238579888f477e981f998265031adf95218-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1",
    "aws_appsync_graphqlEndpoint": "https://qqieqhyoznbdrocc4423mtuosm.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-dgrxiiisardp5i4jvjsdnbqcxq",
    "aws_content_delivery_bucket": "ookstore-20221014214828-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ca-central-1",
    "aws_content_delivery_url": "http://ookstore-20221014214828-hostingbucket-dev.s3-website.ca-central-1.amazonaws.com"
};


export default awsmobile;
